language: go
go:
    - 1.x
    - master
matrix:
    allow_failures:
        - go: master
before_install:
    - sudo apt-get upgrade
    - sudo apt-get install -yy lxc-dev
install: make
script: make check
