sudo: required
dist: xenial
language: go
go:
    - 1.x
    - master
matrix:
    allow_failures:
        - go: master
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-lxc/lxc-git-master
    - sudo add-apt-repository -y ppa:projectatomic/ppa
    - sudo apt-get update
    - sudo apt-get install -yy lxc-utils lxc-dev libacl1-dev skopeo jq libcap-dev libgpgme11-dev
script:
    - env GO111MODULE=on make check
